### PR TITLE
Fix #4: Build failure with master version of math-comp.

### LINKED ISSUE #4: Build failure with master version of math-comp
Here is the error message:

~~~
File "./theories/PFsection3.v", line 580, characters 55-61:
Error:
Syntax error: '<-' expected after [Prim.name] (in [constr:operconstr]).
~~~

### PR DESCRIPTION
**Pull request by ppedrot**
Quite urgent.

Fixes #4.

### CODE REVIEW

**Comment by amahboubi** [comment]
Thanks! I agree it's urgent, but I am not sure about the choice @CohenCyril and @ggonthier want to make to fix this. There might be a notation declaration to be fixed somewhere.

**Comment by ppedrot** [comment]
Well, this PR is but a hotfix, so it doesn't prevent thinking about the proper way to repair thiswhile allowing the Coq CI to remain green.

**Comment by amahboubi** [comment]
Agreed.

**Comment by ggonthier** [comment]
I'm afraid that was the wrong fix. The culprit here is the `allsigs` branch merge, which introduced syntax that clashes with the existing syntax for filtered maps, and more generally is inconsistent with the math comp syntax for comprehensions, in which `&` always introduces a filtering condition. Therefore the right hot fix is to roll back the merge and clean up the branch before moving forward again.
  In this case the correct syntax would be to use `,` as a separator. That syntax is used by `allpairs`, hence the alternate (and unfortunate) choice of punctuation. One solution would be to use a less conflictual alternative, such as `;`, but in my opinion the better option would be to simply generalise the definition of `allpairs`, since applying `allsigs` to a constant `t` is convertible to the result of applying `allpairs`. In fact, it's questionable whether a new constant is useful at all, since just defining `[seq E | i <- s, j <- t]` as `Notation` for `flatten [seq [seq E | j <- t] | i <- s]` would work just as well...
 Of course one would still keep two sets of lemmas for the dependent and non-dependent cases.

**Pull request merged**
