### PR TITLE
[wip] port to HB

### PR DESCRIPTION
**Pull request by gares**
It passes, there are mainly 3 problems:
- the FO step of rewrite kicks in is a different way, and a few rewrite have to be made more precise
- a perf problem with a hint extern declared in ssrnum
- HB.pack is uber slow in a few cases

### CODE REVIEW

**Comment by gares** [comment]
Help @CohenCyril for nix

**Comment by gares** [comment]
you should be able to push to this branch now

**Comment by proux01** [comment]
Done (took me a while to figure out the name of the branch is `hirarchy-builder` without `e` :cry:)

**Comment by gares** [comment]
surely a typo from me, sorry

**Comment by gares** [comment]
Thanks apparently it was not that hard, but I got tired and missed a /= and thought it was a deep problem.

**Comment by proux01** [comment]
Actually, the additional `/=` are less painful (except maybe when they require repeating a `!` rewrite) than the (very few, only 5 instances here) associativity rewrite that require an additional pattern (but nothing specific to semirings here, we already experienced that with the HB port of mathcomp).

**Pull request merged**
